# Wallpaper for all monitors (set by matugen)
wallpaper {
    monitor =
    path = /home/athoms/dotfiles/wallpapers/gargantua-black-1920x1200-9621.jpg
    fit_mode = cover
}

# Misc options
ipc = true
splash = false
splash_offset = 20
splash_opacity = 0.8
