# Fallback wallpaper for all monitors
wallpaper {
    monitor =
    path = ~/dotfiles/wallpapers/anime_room3.png
    fit_mode = cover
}

# Misc options
ipc = true
splash = false
splash_offset = 20
splash_opacity = 0.8
